# Generated by Django 2.1.7 on 2021-07-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventplanner', '0002_userprofile_usertype'),
        ('event_manager', '0003_manage_book_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('num_of_mem', models.IntegerField()),
                ('user_remark', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('e_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.Event')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventplanner.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
