# Generated by Django 2.1.7 on 2021-07-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
