# Generated by Django 2.1.7 on 2021-07-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_auto_20210712_0936'),
        ('eventplanner', '0002_userprofile_usertype'),
        ('event_user', '0003_auto_20210709_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('num_of_person', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('catering', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('prices', models.IntegerField()),
                ('decoration_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.decoration_theme')),
                ('ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.events')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventplanner.UserProfile')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.venue')),
            ],
        ),
    ]
