# Generated by Django 2.1.7 on 2021-07-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_user', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
