# Generated by Django 2.1.7 on 2021-07-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
