# Generated by Django 2.1.7 on 2021-07-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventplanner', '0002_userprofile_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('dated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('eve_img', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('location', models.CharField(max_length=50, null=True)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('speaker_name', models.CharField(max_length=100, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventplanner.UserProfile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.category')),
            ],
        ),
        migrations.CreateModel(
            name='manage_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_remark', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sponsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponser', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='product_image')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sponsers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manager.sponsers'),
        ),
    ]
