# Generated by Django 2.1.7 on 2021-07-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_book',
            name='admin_remark',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
