# Generated by Django 2.1.7 on 2021-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_auto_20210707_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_book',
            name='action',
            field=models.CharField(choices=[('confirm', 'confirm'), ('cancel', 'cancel')], max_length=10, null=True),
        ),
    ]
