# Generated by Django 2.1.7 on 2021-07-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner', '0002_userprofile_usertype'),
        ('event_manager', '0003_manage_book_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='decoration_theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='event1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eve_img', models.ImageField(upload_to='product_image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventplanner.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ven', models.CharField(max_length=50)),
            ],
        ),
    ]
