# Generated by Django 2.1.7 on 2021-07-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner', '0002_userprofile_usertype'),
        ('event_manager', '0004_decoration_theme_event1_venue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event1',
            new_name='events',
        ),
    ]
